version: '3.5'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./framework:/var/www/app
      - ./nginx-site.conf:/etc/nginx/conf.d/docker.conf
    links:
      - php-fpm
  php-fpm:
    image: php:8-fpm
    build:
      dockerfile: Dockerfile
    volumes:
      - ./framework:/var/www/app
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3386:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
